# Adapted from https://qvault.io/2019/08/08/automatic-cross-platform-deployments-with-electron-on-a-ci-server-travis/

language: node_js

node_js:
  - 14

# Always run two parallel builds: one on mac and one on linux
matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      language: node_js
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      dist: focal
      sudo: required
      language: generic

addons:
  homebrew:
    # Fixes issues described in:
    # https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296/14
    update: true
    packages:
      - gsl
      - gcc@7
      - double-conversion
      - boost
      - glib
      - cairo

  apt:
    update: true
    packages:
      - g++
      - cmake
      - libboost-dev
      - libdouble-conversion-dev
      - libgsl-dev
      - libcairo2-dev

notifications:
  email: false
cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
before_install:
  # add git lfs for large file support
  - |
    if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      mkdir -p /tmp/git-lfs && curl -L https://github.com/github/git-lfs/releases/download/v2.3.1/git-lfs-$([ "$TRAVIS_OS_NAME" == "linux" ] && echo "linux" || echo "darwin")-amd64-2.3.1.tar.gz | tar -xz -C /tmp/git-lfs --strip-components 1
      export PATH="/tmp/git-lfs:$PATH"
    fi
before_script:
  - git lfs pull

# on PRs and merges to master and prod run tests and build the app
script:
  - node --version
  - yarn
  - yarn test
# only deploy to github on a merge to the prod branch
deploy:
  provider: script
  script: bash deploy.travis.sh
  skip_cleanup: true
  on:
    # TODO: all merges to master shouldn't trigger release, use prod branch as advised in tutorial and include in only
    branch: master #prod


# only run this script on pull requests and merges into
# the 'master' and 'prod' branches
branches:
  only:
    - master
#    - prod
