image: Visual Studio 2017
environment:
  nodejs_version: "14"
  Path: $(npm config get prefix)\bin;C:\MinGW\bin;$(Path)
  VCPKG_DEFAULT_TRIPLET: x86-windows
  MAKEFLAGS: "SHELL=cmd"

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - c:\tools\vcpkg\installed\
  - $(npm config get prefix)

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  # https://github.com/microsoft/vcpkg/issues/14815
  - choco install pkgconfiglite
  - vcpkg install gsl
  - vcpkg install boost
  - vcpkg install double-conversion
  - vcpkg install cairo
  - npm i -g cmake-js
  # https://www.appveyor.com/docs/windows-images-software/#boost
  - npm config set cmake_CMAKE_TOOLCHAIN_FILE "c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - npm config set cmake_VCPKG_TARGET_TRIPLET x86-windows
  - npm config set cmake_CMAKE_MAKE_PROGRAM:FILEPATH C:\MinGW\bin\make.exe
  - npm config set cmake_CMAKE_C_COMPILER:FILEPATH C:\MinGW\bin\gcc.exe
  - npm config set cmake_CMAKE_CXX_COMPILER:FILEPATH C:\MinGW\bin\g++.exe
  - npm config set cmake_js_G "MinGW Makefiles"
  - npm install

build_script:
  - npm run release --win

test: false
