image: Visual Studio 2017
environment:
  nodejs_version: "14"
  Path: $(yarn global bin);$(Path)
  VCPKG_DEFAULT_TRIPLET: x64-windows

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - c:\tools\vcpkg\installed\
  - $(yarn global bin)
  - $(yarn global dir)

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  # https://github.com/microsoft/vcpkg/issues/14815
  - choco install pkgconfiglite
  - vcpkg install gsl:x64-windows
  - vcpkg install double-conversion:x64-windows
  - vcpkg install cairo:x64-windows
  - yarn global add cmake-js
  # https://www.appveyor.com/docs/windows-images-software/#boost
  - npm config set cmake_BOOST_ROOT "C:\Libraries\boost_1_69_0"
  - npm config set cmake_CMAKE_TOOLCHAIN_FILE "c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - yarn

build_script:
  - yarn release --win

test: false
