image: Visual Studio 2017
environment:
  nodejs_version: "14"
  Path: $(yarn global bin);C:\MinGW\bin;$(Path)
  VCPKG_DEFAULT_TRIPLET: x86-windows

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - c:\tools\vcpkg\installed\
  - $(yarn global bin)
  - $(yarn global dir)

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node $env:nodejs_version
  # https://github.com/microsoft/vcpkg/issues/14815
  - choco install pkgconfiglite
  - vcpkg install gsl
  - vcpkg install boost
  - vcpkg install double-conversion
  - vcpkg install cairo
  - yarn global add cmake-js
  # https://www.appveyor.com/docs/windows-images-software/#boost
  - npm config set cmake_CMAKE_TOOLCHAIN_FILE "c:\tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
  - npm config set cmake_CMAKE_SH "CMAKE_SH-NOTFOUND"
  - npm config set cmake_VCPKG_TARGET_TRIPLET x86-windows
  - npm config set cmake_CMAKE_MAKE_PROGRAM "C:\MinGW\bin\make.exe"
  - npm config set cmake_js_G "MinGW Makefiles"
  - yarn

build_script:
  - yarn release --win

test: false
